apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: order-api
        image: omni-ops-order-api:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: AWS_ENDPOINT_URL
          value: "http://localstack-svc:4566"