name: Omni-Ops CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted # Senin MacBook Pro M3 Runner'ın
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          # Buildx yerine standart build kullanarak yetki sorunlarını aşıyoruz
          docker build -t ${{ secrets.DOCKER_USERNAME }}/omni-ops-order-api:latest -f services/order-api/Dockerfile services/order-api
          docker push ${{ secrets.DOCKER_USERNAME }}/omni-ops-order-api:latest

      - name: Deploy to Minikube
        run: |
          # Yeni imajı Minikube'a çek ve podu tazele
          kubectl rollout restart deployment order-api
          echo "Otomatik dağıtım başarıyla tamamlandı!"